=pod

=head1 NAME

parser.winxed - A simple, minimial parser, which will serve as the basis of
a minimal abstract syntax tree (AST) based expression evaluator.[*]

=head1 SYNOPSIS

=over 4

$ winxed parser.winxed 

=back

=head1 DESCRIPTION

This is a winxed implementation of a simple, minimal parser with which to
build a simple, minimal abstract syntax tree (AST) based expression
evaluator.[1]

=head1 NOTES

[*] This example implementation is, at present, I<very> incomplete. 

[1] The purpose of this program is to serve as something of a tutorial on how
to write a simple, minimal AST-based expression evaluator in the Winxed
programming language.

=head1 COPYRIGHT

Copyright (C) 2012, Alvis Yardley

=cut
